apiVersion: v1
kind: Secret
metadata:
  name: myasso-secrets
  namespace: default
type: Opaque
stringData:
  # Mot de passe root MySQL (changez-le en production !)
  mysql-root-password: rootpassword123
  # Mot de passe utilisateur MySQL
  mysql-password: myassopassword123
  # Secret JWT pour l'authentification
  jwt-secret: changez_cette_cle_secrete_en_production_k8s

